name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.unsupported }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', head]
        unsupported: [false]
        include:
          - ruby-version: '2.4'
            unsupported: true
          - ruby-version: '2.5'
            unsupported: true
          - ruby-version: '2.6'
            unsupported: true

    steps:
    - uses: actions/checkout@v3
    - name: Remove Gemfile.lock
      run: rm -f Gemfile.lock
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.113.3
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake test
      continue-on-error: ${{ matrix.unsupported }}
    - name: Run man tests
      run: bundle exec rake man

  rubocop:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.113.3
      with:
        ruby-version: 2.7.6
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run RuboCop
      run: bundle exec rubocop
