# We do not have plan to support 
name: JRuby

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [jruby-9.2.9.0, jruby-head]
    continue-on-error: true

    steps:
    - uses: actions/checkout@v3
    - name: Remove Gemfile.lock
      run: rm -f Gemfile.lock
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.113.3
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake test
      continue-on-error: true
    - name: Run man tests
      run: bundle exec rake man
      continue-on-error: true
